// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52IXD8wS2U6B3xYkWWyX3kHITvLYTKmk',
    appId: '1:873141701837:web:19e398da0b100734c96d84',
    messagingSenderId: '873141701837',
    projectId: 'flutter-auth-app-2f23c',
    authDomain: 'flutter-auth-app-2f23c.firebaseapp.com',
    storageBucket: 'flutter-auth-app-2f23c.firebasestorage.app',
    measurementId: 'G-8QJ8NS6XJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLFdA1p5dW7smFquxYyfXoXq2oxNKOTk',
    appId: '1:873141701837:android:4eed8c7866373478c96d84',
    messagingSenderId: '873141701837',
    projectId: 'flutter-auth-app-2f23c',
    storageBucket: 'flutter-auth-app-2f23c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChL5DBRQPO5ZilsAIv6KsUps4JBVESEZw',
    appId: '1:873141701837:ios:f2cc629d9a08aedbc96d84',
    messagingSenderId: '873141701837',
    projectId: 'flutter-auth-app-2f23c',
    storageBucket: 'flutter-auth-app-2f23c.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChL5DBRQPO5ZilsAIv6KsUps4JBVESEZw',
    appId: '1:873141701837:ios:f2cc629d9a08aedbc96d84',
    messagingSenderId: '873141701837',
    projectId: 'flutter-auth-app-2f23c',
    storageBucket: 'flutter-auth-app-2f23c.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52IXD8wS2U6B3xYkWWyX3kHITvLYTKmk',
    appId: '1:873141701837:web:7a87f4f6be47f686c96d84',
    messagingSenderId: '873141701837',
    projectId: 'flutter-auth-app-2f23c',
    authDomain: 'flutter-auth-app-2f23c.firebaseapp.com',
    storageBucket: 'flutter-auth-app-2f23c.firebasestorage.app',
    measurementId: 'G-KFP4FN6EHR',
  );
}
